services:
  - type: web
    name: granabot-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm install && node prepare-deploy.js && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: granabot-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: WEB_APP_URL
        sync: false

databases:
  - name: granabot-db
    databaseName: granabot
    user: granabot
    plan: free
